"""
src/output/templates.py

Markdown format templates for all pipeline output documents.
Uses Python str.format() placeholders ({{field_name}}).
"""

# ── PRD Template ──────────────────────────────────────────────────────────────

PRD_TEMPLATE = """\
# {title}

| Field | Value |
|---|---|
| **Version** | {version} |
| **Status** | {status} |
| **Generated** | {generated_date} |
| **Engineering Quality Score** | {final_score}/10 |

---

## 1. Executive Summary

{executive_summary}

---

## 2. Problem Statement

{problem_statement}

---

## 3. Goals and Success Metrics

{goals_and_metrics}

---

## 4. User Stories

{user_stories}

---

## 5. Acceptance Criteria

{acceptance_criteria}

---

## 6. Non-Goals and Out of Scope

{non_goals}

---

## 7. Technical Feasibility Assessment

> _Reviewed by Engineering Agent_

{technical_assessment}

---

## 8. Open Questions and Risks

{open_questions}

---

## 9. Source Evidence

> _Representative quotes and data points from ingested customer feedback_

{source_evidence}

---

## Appendix A: Engineering Review Log

{critique_log}

---

_This document was generated by the Autonomous PM Engine._
_All claims are grounded in ingested customer feedback data._
"""

# ── Roadmap Template ──────────────────────────────────────────────────────────

ROADMAP_TEMPLATE = """\
# Engineering Roadmap: {title}

**Generated:** {generated_date}

> Features are ordered by RICE score (Reach x Impact x Confidence / Effort).
> Quarterly assignments are initial proposals; engineering leads should
> validate effort estimates before committing to sprint schedules.

---

## Feature Impact Summary

| Rank | Feature | Category | Total Mentions | Pain Points |
|---|---|---|---|---|
{features_table}

---

## {year} Quarterly Plan

### Q1 — Foundation and Quick Wins

**Objective:** Address the highest-frequency pain points to demonstrate immediate value.

{q1_features}

**Definition of Done:**
- All acceptance criteria from PRD Section 5 met
- Unit test coverage >= 80%
- Load tested at 2x expected peak traffic
- Accessibility audit passed (WCAG 2.1 AA)

---

### Q2 — Core Feature Build-Out

**Objective:** Deliver the primary feature set that resolves the top theme clusters.

{q2_features}

**Definition of Done:**
- Integration tests passing in staging environment
- Feature flag deployed to 10% of users (canary)
- Performance SLO verified: p95 latency < 200ms
- Documentation and release notes complete

---

### Q3 — Depth and Integrations

**Objective:** Extend core features with integrations and advanced capabilities.

{q3_features}

**Definition of Done:**
- End-to-end tests covering all new integration paths
- Security review completed
- Full rollout to 100% of eligible users
- Monitoring dashboards live

---

### Q4 — Reliability, Observability, and Debt Reduction

**Objective:** Harden the system and address technical debt surfaced during Q1-Q3.

{q4_features}

**Definition of Done:**
- Zero P0/P1 bugs open for >48 hours
- On-call runbooks updated
- Tech debt items resolved or scheduled
- Retrospective completed and learnings documented

---

## Cross-Cutting Concerns (All Quarters)

| Area | Requirement |
|---|---|
| **Security** | Quarterly penetration test; OWASP Top 10 compliance |
| **Accessibility** | WCAG 2.1 AA; screen reader compatibility |
| **Performance** | p95 API response time < 200ms; p99 < 500ms |
| **Observability** | All new endpoints instrumented with traces, logs, metrics |
| **Documentation** | API docs auto-generated; user-facing changelog maintained |

---

_This roadmap was generated by the Autonomous PM Engine._
"""

# ── Priority Matrix Template ──────────────────────────────────────────────────

PRIORITY_MATRIX_TEMPLATE = """\
# Feature Priority Matrix (RICE Scoring)

**Generated:** {generated_date}

## Scoring Methodology

**RICE = (Reach x Impact x Confidence) / Effort**

| Variable | Definition | Scale |
|---|---|---|
| **Reach** | Estimated number of users affected per quarter | Raw number |
| **Impact** | How significantly does this solve the problem? | 1 (minimal) to 10 (massive) |
| **Confidence** | How confident are we in the estimates? | 0.5 (low) / 0.8 (medium) / 1.0 (high) |
| **Effort** | Engineering effort in person-weeks | 1 (trivial) to 10 (large) |

> RICE scores are computed from customer feedback signal (mention frequency and
> pain-point count). They are starting points for discussion, not final verdicts.
> Engineering teams should refine effort estimates in sprint planning.

---

## Feature Rankings

| Feature | Category | Reach | Impact | Confidence | Effort | RICE Score |
|---|---|---|---|---|---|---|
{rows}

---

## Interpretation Guide

| RICE Score | Priority Tier | Recommended Action |
|---|---|---|
| > 500 | P0 — Critical | Ship this quarter; assign senior engineers |
| 200-500 | P1 — High | Schedule within next two quarters |
| 100-200 | P2 — Medium | Backlog; revisit next planning cycle |
| < 100 | P3 — Low | Defer or consider dropping |

---

_This matrix was generated by the Autonomous PM Engine._
_Re-run after each major feedback collection cycle to keep scores current._
"""
